"""changed columns names on table: SubjectTheory

Revision ID: 24b374495ce6
Revises: dffdbdbc9434
Create Date: 2024-03-23 15:13:42.054791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b374495ce6'
down_revision: Union[str, None] = 'dffdbdbc9434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_theory', sa.Column('theory_id', sa.Integer(), nullable=False))
    op.add_column('subject_theory', sa.Column('theory_title', sa.String(), nullable=False))
    op.add_column('subject_theory', sa.Column('theory_data', sa.String(), nullable=False))
    op.drop_constraint('subject_theory_topic_title_key', 'subject_theory', type_='unique')
    op.create_unique_constraint(None, 'subject_theory', ['theory_title'])
    op.drop_constraint('subject_theory_topic_id_fkey', 'subject_theory', type_='foreignkey')
    op.create_foreign_key(None, 'subject_theory', 'subjects', ['theory_id'], ['subject_id'], ondelete='CASCADE')
    op.drop_column('subject_theory', 'topic_title')
    op.drop_column('subject_theory', 'topic_data')
    op.drop_column('subject_theory', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_theory', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subject_theory', sa.Column('topic_data', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('subject_theory', sa.Column('topic_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subject_theory', type_='foreignkey')
    op.create_foreign_key('subject_theory_topic_id_fkey', 'subject_theory', 'subjects', ['topic_id'], ['subject_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'subject_theory', type_='unique')
    op.create_unique_constraint('subject_theory_topic_title_key', 'subject_theory', ['topic_title'])
    op.drop_column('subject_theory', 'theory_data')
    op.drop_column('subject_theory', 'theory_title')
    op.drop_column('subject_theory', 'theory_id')
    # ### end Alembic commands ###
