"""add is done column to teacher_info

Revision ID: 5afb3ec62065
Revises: f3d876ae1b36
Create Date: 2024-03-26 17:57:02.267625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5afb3ec62065'
down_revision: Union[str, None] = 'f3d876ae1b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_information', sa.Column('is_done', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_information', 'is_done')
    # ### end Alembic commands ###
