"""fix: test subject theory adding

Revision ID: 930cfb30c549
Revises: b7ae9d172fdd
Create Date: 2024-04-11 11:07:18.931763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '930cfb30c549'
down_revision: Union[str, None] = 'b7ae9d172fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject_theory', 'theory_title',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Заголовок теории')
    op.alter_column('subject_theory', 'theory_data',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Данные теории (файл, текст, ссылка)')
    op.drop_constraint('subject_theory_theory_title_key', 'subject_theory', type_='unique')
    op.create_table_comment(
        'subject_theory',
        'Теория для предмета. У каждого предмета может быть только одна теория в виде файла',
        existing_comment='Теория для предмета. У каждого предмета может быть только одна теория',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'subject_theory',
        'Теория для предмета. У каждого предмета может быть только одна теория',
        existing_comment='Теория для предмета. У каждого предмета может быть только одна теория в виде файла',
        schema=None
    )
    op.create_unique_constraint('subject_theory_theory_title_key', 'subject_theory', ['theory_title'])
    op.alter_column('subject_theory', 'theory_data',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Данные теории (файл, текст, ссылка)')
    op.alter_column('subject_theory', 'theory_title',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Заголовок теории')
    # ### end Alembic commands ###
