"""delete completed from subjects table and add owner for subject

Revision ID: 95382995b099
Revises: b74e80281ba9
Create Date: 2024-03-19 22:53:08.105077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95382995b099'
down_revision: Union[str, None] = 'b74e80281ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('completed', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'subject_tasks', ['subject_task_id'])
    op.add_column('subjects', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subjects', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('subjects', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'user_id')
    op.drop_constraint(None, 'subject_tasks', type_='unique')
    op.drop_column('enrollments', 'completed')
    # ### end Alembic commands ###
