"""fix: delete column theory title on SubjectTheory table

Revision ID: af168ebe5a0f
Revises: 930cfb30c549
Create Date: 2024-04-11 12:02:43.220825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af168ebe5a0f'
down_revision: Union[str, None] = '930cfb30c549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject_theory', 'theory_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject_theory', sa.Column('theory_title', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Заголовок теории'))
    # ### end Alembic commands ###
