"""add new table subject_tasks_and_other

Revision ID: b74e80281ba9
Revises: 2999ce04298b
Create Date: 2024-03-19 22:32:20.604689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74e80281ba9'
down_revision: Union[str, None] = '2999ce04298b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_tasks',
    sa.Column('subject_task_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_task_id'),
    sa.UniqueConstraint('subject_task_id'),
    sa.UniqueConstraint('task_name')
    )
    op.add_column('subjects', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'completed')
    op.drop_table('subject_tasks')
    # ### end Alembic commands ###
