"""fix: bug

Revision ID: b7ae9d172fdd
Revises: ebfcd4eaae4b
Create Date: 2024-04-08 09:11:01.696925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ae9d172fdd'
down_revision: Union[str, None] = 'ebfcd4eaae4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
