"""add image to subject

Revision ID: c7c465dafaea
Revises: 5afb3ec62065
Create Date: 2024-03-27 09:14:28.761599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c465dafaea'
down_revision: Union[str, None] = '5afb3ec62065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('subject_image', sa.String(), server_default='subject_image.png', nullable=False, comment='Изображения для предмета'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'subject_image')
    # ### end Alembic commands ###
