"""add new table: TaskGrades

Revision ID: c8606154fd3b
Revises: 0b52be9e2b4a
Create Date: 2024-03-31 16:41:25.764019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8606154fd3b'
down_revision: Union[str, None] = '0b52be9e2b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_grades',
    sa.Column('task_grade_id', sa.Integer(), nullable=False, comment='Идентификатор оценки за задание'),
    sa.Column('enrollment_id', sa.Integer(), nullable=False, comment='Идентификатор записи о подписке'),
    sa.Column('subject_task_id', sa.Integer(), nullable=False, comment='Идентификатор задания'),
    sa.Column('grade_value', sa.Integer(), nullable=False, comment='Оценка за задание'),
    sa.Column('grade_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата постановки оценки'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.enrollment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_task_id'], ['subject_tasks.subject_task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_grade_id'),
    comment='Оценки за задания по предметам'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_grades')
    # ### end Alembic commands ###
