"""remove unique field from subject_tasks

Revision ID: cdd169f2309f
Revises: c7c465dafaea
Create Date: 2024-03-30 20:41:27.356783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd169f2309f'
down_revision: Union[str, None] = 'c7c465dafaea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subject_tasks_task_name_key', 'subject_tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('subject_tasks_task_name_key', 'subject_tasks', ['task_name'])
    op.create_table('completed_task_status',
    sa.Column('subject_task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject_task_id'], ['subject_tasks.subject_task_id'], name='completed_task_status_subject_task_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='completed_task_status_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_task_id', 'user_id', name='completed_task_status_pkey')
    )
    # ### end Alembic commands ###
