"""add new relation to taskgrades: user_id

Revision ID: d21ad2c53e5d
Revises: c8606154fd3b
Create Date: 2024-03-31 17:55:24.908409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21ad2c53e5d'
down_revision: Union[str, None] = 'c8606154fd3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'grades',
        'Итоговая оценка студентов по предметам',
        existing_comment='Оценки студентов по предметам',
        schema=None
    )
    op.add_column('task_grades', sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя, который выполнил задание'))
    op.create_foreign_key(None, 'task_grades', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_grades', type_='foreignkey')
    op.drop_column('task_grades', 'user_id')
    op.create_table_comment(
        'grades',
        'Оценки студентов по предметам',
        existing_comment='Итоговая оценка студентов по предметам',
        schema=None
    )
    # ### end Alembic commands ###
