"""add teacher information table

Revision ID: da6129c2edcd
Revises: 7f6a0bf3ac6a
Create Date: 2024-03-26 16:09:13.964991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6129c2edcd'
down_revision: Union[str, None] = '7f6a0bf3ac6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_information',
    sa.Column('teacher_information_id', sa.Integer(), autoincrement=True, nullable=False, comment='идентификатор информации'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='id пользователя'),
    sa.Column('teacher_experience', sa.Integer(), nullable=False, comment='опыт преподавателя'),
    sa.Column('teacher_description', sa.String(), nullable=False, comment='Информация о преподавателе'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_information_id'),
    comment='Дополнительная информация о преподавателе'
    )
    op.alter_column('user_task_files', 'user_id',
               existing_type=sa.INTEGER(),
               comment='пользователь',
               existing_nullable=False)
    op.alter_column('user_task_files', 'enrollment_id',
               existing_type=sa.INTEGER(),
               comment='предмет на который записан пользователй',
               existing_nullable=False)
    op.alter_column('user_task_files', 'task_file',
               existing_type=sa.VARCHAR(),
               comment='файл прикрепленный к заданию',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_task_files', 'task_file',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='файл прикрепленный к заданию',
               existing_nullable=False)
    op.alter_column('user_task_files', 'enrollment_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='предмет на который записан пользователй',
               existing_nullable=False)
    op.alter_column('user_task_files', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='пользователь',
               existing_nullable=False)
    op.drop_table('teacher_information')
    # ### end Alembic commands ###
