"""fix: bug

Revision ID: ebfcd4eaae4b
Revises: f22a63be70d8
Create Date: 2024-04-07 18:31:56.704456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfcd4eaae4b'
down_revision: Union[str, None] = 'f22a63be70d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_grades', 'enrollment_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Идентификатор записи о подписке')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_grades', 'enrollment_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Идентификатор записи о подписке')
    # ### end Alembic commands ###
