"""db.v.0.0.1

Revision ID: f22a63be70d8
Revises: d21ad2c53e5d
Create Date: 2024-04-01 09:33:32.904481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22a63be70d8'
down_revision: Union[str, None] = 'd21ad2c53e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
