"""add relationship

Revision ID: f3d876ae1b36
Revises: bdf3b36e1edf
Create Date: 2024-03-26 16:51:38.850030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d876ae1b36'
down_revision: Union[str, None] = 'bdf3b36e1edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher_information', 'teacher_experience',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='опыт преподавателя')
    op.alter_column('teacher_information', 'teacher_description',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='Информация о преподавателе')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher_information', 'teacher_description',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='Информация о преподавателе')
    op.alter_column('teacher_information', 'teacher_experience',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='опыт преподавателя')
    # ### end Alembic commands ###
